# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the Node.js 18.x image as the base
FROM node:18-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the entire source directory to the container
COPY . .

# Build the TypeScript project
RUN npm run build

# Prepare the production image
FROM node:18-alpine

# Set the working directory inside the production container
WORKDIR /app

# Copy the build artifacts and necessary files from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY package.json ./

# Set environment variables for Trello API keys
ENV TRELLO_API_KEY=your_api_key
ENV TRELLO_TOKEN=your_token

# Expose the necessary port
EXPOSE 3000

# Command to run the MCP server
CMD ["node", "build/index.js"]